# our base image
FROM python:3.9
# Install python and pip
# RUN apk add --update py2-pip
# upgrade pip
RUN pip install --upgrade pip
# install Python modules needed by the Python app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
# copy files required for the app to run
COPY main.py /usr/src/app/
COPY templates/* /usr/src/app/templates/
COPY static/* /usr/src/app/static/
COPY static/tflite/* /usr/src/app/static/tflite/
COPY tfmodel.py /usr/src/app/
COPY keys/* /usr/src/app/keys/
COPY VisionAPI.py /usr/src/app/
# Extra
ENV GOOGLE_CLOUD_PROJECT=proj8824
# tell the port number the container should expose
EXPOSE 8080
# run the application   
CMD ["python", "/usr/src/app/main.py"]
